Created base script to display a help button
newfold-labs/wp-module-help-center pull request #1
Opened 2023-01-09 04:30 UTC by ashrithapradeep

2023-02-23 15:03 UTC, wpscholar requested changes

2023-02-23 15:03 UTC, wpscholar commented on src/components/Modal.js
> +        <h3 className="heading">Need help?</h3>
We should be using the WordPress translation function here so this can be translated.

2023-02-23 15:03 UTC, wpscholar commented on src/components/Suggestions.js
> +                  <h4 className="section-header">Videos</h4>
We should make this text translatable

2023-02-23 15:03 UTC, wpscholar commented on src/components/Suggestions.js
> +                  <h4 className="section-header">Articles</h4>
We should make this text translatable

2023-03-10 09:21 UTC, aulisius requested changes

2023-03-10 09:21 UTC, aulisius commented on src/components/LaunchHelpCenter.js
> +  const enableHelp = async () => {
Use `swr/mutation`

2023-03-10 09:21 UTC, aulisius commented on modal.scss
> +.modal {
Push under nfd help center namespace

2023-03-10 09:21 UTC, aulisius commented on src/components/NoSuggestionsFound.js
> +        In the meantime, try searching our <a>Resource center.</a>
TODO: Add link for resource center

2023-03-10 09:21 UTC, aulisius commented on src/components/Suggestions.js
> +                      className="video"
Add `key` prop

2023-05-26 08:07 UTC, merged